name: Build

on:
  pull_request:
  push:
    branches: [ main, rp2040CI ]

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate matrix (JSON)
        id: gen
        run: |
          python3 .github/gen_mcu_matrix.py >> "$GITHUB_OUTPUT"

  build:
    needs: discover
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.discover.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ join(matrix.apt, ' ') }}

      - name: SDK fetch
        run: python3 .github/fetch_sdk.py '${{ toJson(matrix.sdk) }}'

      - name: Configure (${{ matrix.id }} - ${{ matrix.desc }})
        run: >
          cmake -S . -B build/${{ matrix.id }} -G Ninja
          ${{ join(matrix.cmake_args, ' ') }}

      - name: Build (${{ matrix.id }})
        run: cmake --build build/${{ matrix.id }} --config Release -j

      - name: Sizes
        run: |
          find build/${{ matrix.id }} -name '*.a' -print -exec arm-none-eabi-size {} \; || true
          find build/${{ matrix.id }} -name '*.a' -print -exec ls -lh {} \; || true


