name: Quality
on:
  pull_request:
  push: { branches: [ main ] }

jobs:
  lint-and-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy cppcheck doxygen graphviz python3-pip
          pip3 install lizard
      - name: Pre-commit checks
        run: |
          mkdir -p docs
          pip3 install pre-commit
          pre-commit run --all-files
